//! Metadata checks.
//!
//! Validates .PKGINFO content for completeness and correctness:
//! required fields, valid values, missing descriptions, etc.

use super::rules::{LintResult, Severity};

/// Required fields that must be present in .PKGINFO.
const REQUIRED_FIELDS: &[&str] = &["pkgname", "pkgver", "pkgdesc", "arch", "size"];

/// Run metadata checks on the .PKGINFO content.
pub fn check_metadata(pkginfo: &str, result: &mut LintResult) {
    check_required_fields(pkginfo, result);
    check_description(pkginfo, result);
    check_pkgver_format(pkginfo, result);
}

/// Check that all required fields are present.
fn check_required_fields(pkginfo: &str, result: &mut LintResult) {
    for field in REQUIRED_FIELDS {
        let prefix = format!("{field} = ");
        if !pkginfo.lines().any(|l| l.starts_with(&prefix)) {
            result.add(
                Severity::Error,
                "metadata-missing-field",
                &format!("required field '{field}' missing from .PKGINFO"),
                None,
            );
        }
    }
}

/// Check that the package description is not empty or just placeholder text.
fn check_description(pkginfo: &str, result: &mut LintResult) {
    for line in pkginfo.lines() {
        if let Some(desc) = line.strip_prefix("pkgdesc = ") {
            let desc = desc.trim();
            if desc.is_empty() {
                result.add(
                    Severity::Warning,
                    "metadata-empty-description",
                    "package description is empty",
                    None,
                );
            } else if desc.starts_with("TODO") || desc.starts_with("FIXME") {
                result.add(
                    Severity::Warning,
                    "metadata-placeholder-description",
                    "package description appears to be a placeholder",
                    None,
                );
            }
            return;
        }
    }
}

/// Check pkgver format (should be version-release).
fn check_pkgver_format(pkginfo: &str, result: &mut LintResult) {
    for line in pkginfo.lines() {
        if let Some(ver) = line.strip_prefix("pkgver = ") {
            let ver = ver.trim();
            if !ver.contains('-') {
                result.add(
                    Severity::Warning,
                    "metadata-pkgver-no-release",
                    "pkgver should follow 'version-release' format (e.g. 1.0-1)",
                    None,
                );
            }
            if ver.is_empty() {
                result.add(
                    Severity::Error,
                    "metadata-empty-pkgver",
                    "pkgver is empty",
                    None,
                );
            }
            return;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn valid_pkginfo() -> String {
        "# Generated by xpkg\n\
         pkgname = hello\n\
         pkgver = 1.0-1\n\
         pkgdesc = Hello world program\n\
         arch = x86_64\n\
         size = 12345\n"
            .to_string()
    }

    #[test]
    fn test_valid_pkginfo_no_issues() {
        let mut result = LintResult::new();
        check_metadata(&valid_pkginfo(), &mut result);
        assert_eq!(result.count(Severity::Error), 0);
        assert_eq!(result.count(Severity::Warning), 0);
    }

    #[test]
    fn test_missing_required_field() {
        let info = "pkgname = hello\npkgver = 1.0-1\n";
        let mut result = LintResult::new();
        check_metadata(info, &mut result);
        assert!(result.has_errors());
        assert!(result
            .diagnostics
            .iter()
            .any(|d| d.message.contains("pkgdesc")));
    }

    #[test]
    fn test_empty_description() {
        let info = "pkgname = hello\npkgver = 1.0-1\npkgdesc = \narch = x86_64\nsize = 0\n";
        let mut result = LintResult::new();
        check_metadata(info, &mut result);
        assert!(result
            .diagnostics
            .iter()
            .any(|d| d.rule == "metadata-empty-description"));
    }

    #[test]
    fn test_placeholder_description() {
        let info =
            "pkgname = hello\npkgver = 1.0-1\npkgdesc = TODO: fill in\narch = x86_64\nsize = 0\n";
        let mut result = LintResult::new();
        check_metadata(info, &mut result);
        assert!(result
            .diagnostics
            .iter()
            .any(|d| d.rule == "metadata-placeholder-description"));
    }

    #[test]
    fn test_pkgver_missing_release() {
        let info = "pkgname = hello\npkgver = 1.0\npkgdesc = Hi\narch = x86_64\nsize = 0\n";
        let mut result = LintResult::new();
        check_metadata(info, &mut result);
        assert!(result
            .diagnostics
            .iter()
            .any(|d| d.rule == "metadata-pkgver-no-release"));
    }
}
